//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolePlayGUI.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RolePlayGUI.Resources.Language.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual event:.
        /// </summary>
        internal static string actualEvent {
            get {
                return ResourceManager.GetString("actualEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base point:.
        /// </summary>
        internal static string basePoint {
            get {
                return ResourceManager.GetString("basePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number and type of dice:.
        /// </summary>
        internal static string diceInstruction {
            get {
                return ResourceManager.GetString("diceInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give a name for the new role-play game!.
        /// </summary>
        internal static string errorAddNameNewGame {
            get {
                return ResourceManager.GetString("errorAddNameNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; game!.
        /// </summary>
        internal static string errorFromGame {
            get {
                return ResourceManager.GetString("errorFromGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string errorNotFound {
            get {
                return ResourceManager.GetString("errorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; player is not found!.
        /// </summary>
        internal static string errorNotFoundPlayer {
            get {
                return ResourceManager.GetString("errorNotFoundPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program could not know to load the players form &quot;.
        /// </summary>
        internal static string errorNotLoad {
            get {
                return ResourceManager.GetString("errorNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorTag {
            get {
                return ResourceManager.GetString("errorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        internal static string eventType {
            get {
                return ResourceManager.GetString("eventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra point:.
        /// </summary>
        internal static string extraPoint {
            get {
                return ResourceManager.GetString("extraPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is not saved. Story line will be lose..
        /// </summary>
        internal static string gameIsNotSaved {
            get {
                return ResourceManager.GetString("gameIsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new game.
        /// </summary>
        internal static string generateGame {
            get {
                return ResourceManager.GetString("generateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hu.
        /// </summary>
        internal static string hu {
            get {
                return ResourceManager.GetString("hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task type:.
        /// </summary>
        internal static string ladderTask {
            get {
                return ResourceManager.GetString("ladderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageTag {
            get {
                return ResourceManager.GetString("languageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game.
        /// </summary>
        internal static string loadGame {
            get {
                return ResourceManager.GetString("loadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opponent.
        /// </summary>
        internal static string opponent {
            get {
                return ResourceManager.GetString("opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent point:.
        /// </summary>
        internal static string opponentPoint {
            get {
                return ResourceManager.GetString("opponentPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponet throw too.
        /// </summary>
        internal static string opponentThrowToo {
            get {
                return ResourceManager.GetString("opponentThrowToo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name:.
        /// </summary>
        internal static string playerName {
            get {
                return ResourceManager.GetString("playerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-play story board.
        /// </summary>
        internal static string rolePlayBoard {
            get {
                return ResourceManager.GetString("rolePlayBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill:.
        /// </summary>
        internal static string skill {
            get {
                return ResourceManager.GetString("skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story:.
        /// </summary>
        internal static string story {
            get {
                return ResourceManager.GetString("story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum point:.
        /// </summary>
        internal static string sumPoint {
            get {
                return ResourceManager.GetString("sumPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw dice.
        /// </summary>
        internal static string throwDice {
            get {
                return ResourceManager.GetString("throwDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs..
        /// </summary>
        internal static string vs {
            get {
                return ResourceManager.GetString("vs", resourceCulture);
            }
        }
    }
}
