name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 4.8
      uses: actions/setup-dotnet@sxs-with-fallback
      with:
        dotnet-version: 4.8.03761
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
